<?php


namespace App\Entity;


class Genres
{
    private $genres = array(
        "acoustic" => 0,
        "afrobeat" => 0,
        "alt-rock" => 0,
        "alternative" => 1,
        "ambient" => 0,
        "anime" => 0,
        "black-metal" => 0,
        "bluegrass" => 0,
        "blues" => 0,
        "bossanova" => 0,
        "brazil" => 0,
        "breakbeat" => 1,
        "british" => 1,
        "cantopop" => 1,
        "chicago-house" => 1,
        "children" => 0,
        "chill" => 1,
        "classical" => 0,
        "club" => 1,
        "comedy" => 0,
        "country" => 0,
        "dance" => 1,
        "dancehall" => 1,
        "death-metal" => 0,
        "deep-house" => 1,
        "detroit-techno" => 1,
        "disco" => 1,
        "disney" => 0,
        "drum-and-bass" => 1,
        "dub" => 1,
        "dubstep" => 1,
        "edm" => 1,
        "electro" => 1,
        "electronic" => 1,
        "emo" => 0,
        "folk" => 0,
        "forro" => 0,
        "french" => 0,
        "funk" => 1,
        "garage" => 0,
        "german" => 1,
        "gospel" => 0,
        "goth" => 0,
        "grindcore" => 0,
        "groove" => 1,
        "grunge" => 0,
        "guitar" => 0,
        "happy" => 0,
        "hard-rock" => 0,
        "hardcore" => 1,
        "hardstyle" => 1,
        "heavy-metal" => 0,
        "hip-hop" => 1,
        "holidays" => 0,
        "honky-tonk" => 0,
        "house" => 01,
        "idm" => 1,
        "indian" => 0,
        "indie" => 0,
        "indie-pop" => 1,
        "industrial" => 1,
        "iranian" => 0,
        "j-dance" => 1,
        "j-idol" => 0,
        "j-pop" => 1,
        "j-rock" => 0,
        "jazz" => 0,
        "k-pop" => 0,
        "kids" => 0,
        "latin" => 0,
        "latino" => 0,
        "malay" => 0,
        "mandopop" => 0,
        "metal" => 0,
        "metal-misc" => 0,
        "metalcore" => 0,
        "minimal-techno" => 0,
        "movies" => 0,
        "mpb" => 0,
        "new-age" => 1,
        "new-release" => 1,
        "opera" => 0,
        "pagode" => 0,
        "party" => 1,
        "philippines-opm" => 0,
        "piano" => 1,
        "pop" => 1,
        "pop-film" => 1,
        "post-dubstep" => 1,
        "power-pop" => 1,
        "progressive-house" => 1,
        "psych-rock" => 0,
        "punk" => 0,
        "punk-rock" => 0,
        "r-n-b" => 1,
        "rainy-day" => 1,
        "reggae" => 0,
        "reggaeton" => 0,
        "road-trip" => 1,
        "rock" => 0,
        "rock-n-roll" => 0,
        "rockabilly" => 0,
        "romance" => 0,
        "sad" => 1,
        "salsa" => 0,
        "samba" => 0,
        "sertanejo" => 0,
        "show-tunes" => 0,
        "singer-songwriter" => 0,
        "ska" => 0,
        "sleep" => 0,
        "songwriter" => 0,
        "soul" => 0,
        "soundtracks" => 1,
        "spanish" => 0,
        "study" => 1,
        "summer" => 1,
        "swedish" => 1,
        "synth-pop" => 1,
        "tango" => 0,
        "techno" => 1,
        "trance" => 1,
        "trip-hop" => 1,
        "turkish" => 0,
        "work-out" => 1,
        "world-music" => 1,
    );

    public function setGenresConesense()
    {
        //imposta se un genere è consentito o meno
    }

    public function getGenres()
    {
        return $this->genres;
    }
}